import Head from "next/head";
import { PlayArea } from "./uno_game/playArea";
import { PlayerControls } from "./uno_game/playerControls";
import { Sidebar } from "./uno_game/sidebar";
import { GameState } from "./uno_game/unoContext";

export default function Home() {
  return (
    <>
      <Head>
        <title>Uno</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen max-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <GameState>
          <div className="container grid min-h-screen max-h-screen grid-cols-4 grid-rows-4 gap-4 ">
            <div className="col-start-1 row-span-4 row-start-1 bg-red-300 p-2">
              <Sidebar />
            </div>

            <div className="col-span-3 col-start-2 row-span-3 row-start-1 bg-yellow-300 p-2">
              <PlayArea />
            </div>

            <div className="col-span-3 col-start-2 row-start-4 bg-green-300 p-2">
              <PlayerControls />
            </div>
          </div>
        </GameState>
      </main>
    </>
  );
}
